package adapter

// UpstreamPlatform 描述一个上游 LLM 平台的信息，用于管理台展示和快速接入。
type UpstreamPlatform struct {
	ID            string   `json:"id"`             // 平台唯一标识（与协议名对应）
	Name          string   `json:"name"`           // 平台名称
	Description   string   `json:"description"`    // 平台简介
	Protocol      string   `json:"protocol"`       // 使用的协议适配器
	BaseURL       string   `json:"base_url"`       // 默认 Base URL
	Website       string   `json:"website"`        // 官方网站
	SignupURL     string   `json:"signup_url"`     // API Key 申请页面
	DocsURL       string   `json:"docs_url"`       // API 文档
	PricingURL    string   `json:"pricing_url"`    // 定价页面
	FreeTier      string   `json:"free_tier"`      // 免费额度说明
	Models        []string `json:"models"`         // 代表性模型
	StreamSupport bool     `json:"stream_support"` // 是否支持流式
	Features      []string `json:"features"`       // 特点标签
}

// ListUpstreamPlatforms 返回所有支持的上游平台信息。
func ListUpstreamPlatforms() []UpstreamPlatform {
	return []UpstreamPlatform{
		{
			ID:            "openai",
			Name:          "OpenAI",
			Description:   "GPT 系列模型，行业标杆，支持 GPT-4o、GPT-4o-mini、o1 等模型。",
			Protocol:      "openai",
			BaseURL:       "https://api.openai.com/v1",
			Website:       "https://openai.com",
			SignupURL:     "https://platform.openai.com/api-keys",
			DocsURL:       "https://platform.openai.com/docs",
			PricingURL:    "https://openai.com/pricing",
			FreeTier:      "新用户赠送 $5 额度（限时）",
			Models:        []string{"gpt-4o", "gpt-4o-mini", "o1-preview", "o1-mini", "gpt-3.5-turbo"},
			StreamSupport: true,
			Features:      []string{"Function Calling", "Vision", "JSON Mode", "Embeddings"},
		},
		{
			ID:            "anthropic",
			Name:          "Anthropic Claude",
			Description:   "Claude 系列模型，以长上下文和安全性著称，支持 Claude 3.5 Sonnet、Opus 等。",
			Protocol:      "anthropic",
			BaseURL:       "https://api.anthropic.com",
			Website:       "https://www.anthropic.com",
			SignupURL:     "https://console.anthropic.com/settings/keys",
			DocsURL:       "https://docs.anthropic.com",
			PricingURL:    "https://www.anthropic.com/pricing",
			FreeTier:      "无免费额度，按量付费",
			Models:        []string{"claude-3-5-sonnet-20241022", "claude-3-opus-20240229", "claude-3-haiku-20240307"},
			StreamSupport: true,
			Features:      []string{"200K 上下文", "Tool Use", "Vision", "Prompt Caching"},
		},
		{
			ID:            "azure",
			Name:          "Azure OpenAI",
			Description:   "微软 Azure 云平台上的 OpenAI 服务，企业级安全和合规，支持 GPT-4 系列。",
			Protocol:      "azure",
			BaseURL:       "https://{resource}.openai.azure.com/openai/deployments/{deployment}",
			Website:       "https://azure.microsoft.com/products/ai-services/openai-service",
			SignupURL:     "https://azure.microsoft.com/free",
			DocsURL:       "https://learn.microsoft.com/azure/ai-services/openai",
			PricingURL:    "https://azure.microsoft.com/pricing/details/cognitive-services/openai-service",
			FreeTier:      "Azure 免费账户 $200 额度（30天）",
			Models:        []string{"gpt-4o", "gpt-4o-mini", "gpt-4", "gpt-35-turbo"},
			StreamSupport: true,
			Features:      []string{"企业级合规", "私有网络", "Azure AD 集成", "内容安全"},
		},
		{
			ID:            "gemini",
			Name:          "Google Gemini",
			Description:   "Google 自研 Gemini 系列模型，支持多模态，Gemini 1.5 Pro 支持 1M 上下文。",
			Protocol:      "gemini",
			BaseURL:       "https://generativelanguage.googleapis.com",
			Website:       "https://deepmind.google/technologies/gemini",
			SignupURL:     "https://aistudio.google.com/app/apikey",
			DocsURL:       "https://ai.google.dev/docs",
			PricingURL:    "https://ai.google.dev/pricing",
			FreeTier:      "Gemini 1.5 Flash 免费（限速），Pro 有免费额度",
			Models:        []string{"gemini-1.5-pro", "gemini-1.5-flash", "gemini-1.0-pro", "gemini-embedding"},
			StreamSupport: true,
			Features:      []string{"1M 上下文", "多模态", "Function Calling", "Embeddings"},
		},
		{
			ID:            "bedrock",
			Name:          "AWS Bedrock",
			Description:   "AWS 全托管模型服务，集成 Anthropic、Meta、Amazon 等多家模型，企业级安全。",
			Protocol:      "bedrock",
			BaseURL:       "https://bedrock-runtime.{region}.amazonaws.com",
			Website:       "https://aws.amazon.com/bedrock",
			SignupURL:     "https://aws.amazon.com/free",
			DocsURL:       "https://docs.aws.amazon.com/bedrock",
			PricingURL:    "https://aws.amazon.com/bedrock/pricing",
			FreeTier:      "AWS 免费套餐，部分模型有免费额度",
			Models:        []string{"anthropic.claude-3-sonnet", "meta.llama3-70b", "amazon.titan-text", "ai21.j2-ultra"},
			StreamSupport: true,
			Features:      []string{"多模型选择", "企业级安全", "私有部署", "Bedrock Agents"},
		},
		{
			ID:            "sagemaker",
			Name:          "AWS SageMaker",
			Description:   "AWS 模型部署平台，可自定义部署任意开源模型（vLLM、TGI 等），完全可控。",
			Protocol:      "sagemaker",
			BaseURL:       "https://runtime.sagemaker.{region}.amazonaws.com/endpoints/{endpoint}",
			Website:       "https://aws.amazon.com/sagemaker",
			SignupURL:     "https://aws.amazon.com/free",
			DocsURL:       "https://docs.aws.amazon.com/sagemaker",
			PricingURL:    "https://aws.amazon.com/sagemaker/pricing",
			FreeTier:      "AWS 免费套餐 2 个月（部分实例）",
			Models:        []string{"自定义部署任意开源模型", "Llama 3", "Mixtral", "Qwen"},
			StreamSupport: true,
			Features:      []string{"完全可控", "自定义模型", "自动扩缩容", "A/B 测试"},
		},
		{
			ID:            "cohere",
			Name:          "Cohere",
			Description:   "企业级 NLP 平台，Command 系列模型，擅长 RAG 和企业知识检索。",
			Protocol:      "cohere",
			BaseURL:       "https://api.cohere.ai",
			Website:       "https://cohere.com",
			SignupURL:     "https://dashboard.cohere.com/api-keys",
			DocsURL:       "https://docs.cohere.com",
			PricingURL:    "https://cohere.com/pricing",
			FreeTier:      "免费套餐（限速 10 次/分钟）",
			Models:        []string{"command-r-plus", "command-r", "command-light", "embed-english-v3"},
			StreamSupport: true,
			Features:      []string{"RAG 优化", "企业检索", "多语言", "Embeddings"},
		},
		{
			ID:            "mistral",
			Name:          "Mistral AI",
			Description:   "欧洲 AI 公司，Mistral/Mixtral 系列开源模型，性价比高，支持代码生成。",
			Protocol:      "mistral",
			BaseURL:       "https://api.mistral.ai/v1",
			Website:       "https://mistral.ai",
			SignupURL:     "https://console.mistral.ai/api-keys",
			DocsURL:       "https://docs.mistral.ai",
			PricingURL:    "https://mistral.ai/pricing",
			FreeTier:      "无免费额度，按量付费",
			Models:        []string{"mistral-large-latest", "mistral-medium-latest", "mistral-small-latest", "codestral-latest"},
			StreamSupport: true,
			Features:      []string{"开源模型", "代码生成", "Function Calling", "JSON Mode"},
		},
		{
			ID:            "huggingface",
			Name:          "Hugging Face",
			Description:   "全球最大的开源模型社区，Inference API 支持数万种开源模型，一键调用。",
			Protocol:      "huggingface",
			BaseURL:       "https://api-inference.huggingface.co",
			Website:       "https://huggingface.co",
			SignupURL:     "https://huggingface.co/settings/tokens",
			DocsURL:       "https://huggingface.co/docs/api-inference",
			PricingURL:    "https://huggingface.co/pricing",
			FreeTier:      "免费套餐（限速，模型需排队加载）",
			Models:        []string{"Llama 3", "Mixtral", "Qwen", "Phi-3", "数万种开源模型"},
			StreamSupport: false,
			Features:      []string{"开源模型", "社区驱动", "Datasets", "Spaces"},
		},
		{
			ID:            "replicate",
			Name:          "Replicate",
			Description:   "模型运行平台，支持数万种开源模型，包括图像生成、语音、视频等多模态模型。",
			Protocol:      "replicate",
			BaseURL:       "https://api.replicate.com",
			Website:       "https://replicate.com",
			SignupURL:     "https://replicate.com/account/api-tokens",
			DocsURL:       "https://replicate.com/docs",
			PricingURL:    "https://replicate.com/pricing",
			FreeTier:      "新用户赠送少量免费额度",
			Models:        []string{"LLaMA", "SDXL", "Whisper", "Suno", "数万种模型"},
			StreamSupport: false,
			Features:      []string{"多模态", "图像生成", "语音识别", "视频生成"},
		},
		{
			ID:            "together",
			Name:          "Together AI",
			Description:   "开源模型推理和微调平台，支持 Llama、Mixtral、Qwen 等，低延迟高吞吐。",
			Protocol:      "together",
			BaseURL:       "https://api.together.xyz/v1",
			Website:       "https://www.together.ai",
			SignupURL:     "https://api.together.xyz/settings/api-keys",
			DocsURL:       "https://docs.together.ai",
			PricingURL:    "https://www.together.ai/pricing",
			FreeTier:      "新用户赠送 $5 额度",
			Models:        []string{"Llama 3.1 405B", "Mixtral 8x22B", "Qwen 2.5", "DeepSeek V2"},
			StreamSupport: true,
			Features:      []string{"开源模型", "模型微调", "低延迟", "高吞吐"},
		},
		{
			ID:            "fireworks",
			Name:          "Fireworks AI",
			Description:   "前 Meta AI 团队创立的开源模型推理平台，主打低延迟和高吞吐，性价比高。",
			Protocol:      "fireworks",
			BaseURL:       "https://api.fireworks.ai/inference/v1",
			Website:       "https://fireworks.ai",
			SignupURL:     "https://fireworks.ai/settings/api-keys",
			DocsURL:       "https://docs.fireworks.ai",
			PricingURL:    "https://fireworks.ai/pricing",
			FreeTier:      "新用户赠送 $1 额度",
			Models:        []string{"Llama 3.1 405B", "Mixtral 8x7B", "Qwen 2.5", "DeepSeek V2"},
			StreamSupport: true,
			Features:      []string{"开源模型", "低延迟", "高吞吐", "Function Calling"},
		},
		{
			ID:            "groq",
			Name:          "Groq",
			Description:   "LPU 推理引擎，主打超快推理速度，延迟极低，适合实时对话场景。",
			Protocol:      "groq",
			BaseURL:       "https://api.groq.com/openai/v1",
			Website:       "https://groq.com",
			SignupURL:     "https://console.groq.com/keys",
			DocsURL:       "https://console.groq.com/docs",
			PricingURL:    "https://groq.com/pricing",
			FreeTier:      "免费套餐（限速 14400 请求/天，30 请求/分钟）",
			Models:        []string{"llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768", "gemma2-9b-it"},
			StreamSupport: true,
			Features:      []string{"超快速度", "低延迟", "免费套餐", "开源模型"},
		},
	}
}
