package adapter

// UpstreamPlatform 描述一个上游 LLM 平台的信息，用于管理台展示和快速接入。
type UpstreamPlatform struct {
	ID            string   `json:"id"`             // 平台唯一标识（与协议名对应）
	Name          string   `json:"name"`           // 平台名称
	Description   string   `json:"description"`    // 平台简介
	Protocol      string   `json:"protocol"`       // 使用的协议适配器
	BaseURL       string   `json:"base_url"`       // 默认 Base URL
	Website       string   `json:"website"`        // 官方网站
	SignupURL     string   `json:"signup_url"`     // API Key 申请页面
	DocsURL       string   `json:"docs_url"`       // API 文档
	PricingURL    string   `json:"pricing_url"`    // 定价页面
	FreeTier      string   `json:"free_tier"`      // 免费额度说明
	Models        []string `json:"models"`         // 代表性模型
	StreamSupport bool     `json:"stream_support"` // 是否支持流式
	Features      []string `json:"features"`       // 特点标签
}

// ListUpstreamPlatforms 返回所有支持的上游平台信息。
func ListUpstreamPlatforms() []UpstreamPlatform {
	return []UpstreamPlatform{
		{
			ID:            "openai",
			Name:          "OpenAI",
			Description:   "GPT 系列模型，行业标杆，支持 GPT-4o、GPT-4o-mini、o1 等模型。",
			Protocol:      "openai",
			BaseURL:       "https://api.openai.com/v1",
			Website:       "https://openai.com",
			SignupURL:     "https://platform.openai.com/api-keys",
			DocsURL:       "https://platform.openai.com/docs",
			PricingURL:    "https://openai.com/pricing",
			FreeTier:      "新用户赠送 $5 额度（限时）",
			Models:        []string{"gpt-4o", "gpt-4o-mini", "o1-preview", "o1-mini", "gpt-3.5-turbo"},
			StreamSupport: true,
			Features:      []string{"Function Calling", "Vision", "JSON Mode", "Embeddings"},
		},
		{
			ID:            "anthropic",
			Name:          "Anthropic Claude",
			Description:   "Claude 系列模型，以长上下文和安全性著称，支持 Claude 3.5 Sonnet、Opus 等。",
			Protocol:      "anthropic",
			BaseURL:       "https://api.anthropic.com",
			Website:       "https://www.anthropic.com",
			SignupURL:     "https://console.anthropic.com/settings/keys",
			DocsURL:       "https://docs.anthropic.com",
			PricingURL:    "https://www.anthropic.com/pricing",
			FreeTier:      "无免费额度，按量付费",
			Models:        []string{"claude-3-5-sonnet-20241022", "claude-3-opus-20240229", "claude-3-haiku-20240307"},
			StreamSupport: true,
			Features:      []string{"200K 上下文", "Tool Use", "Vision", "Prompt Caching"},
		},
		{
			ID:            "azure",
			Name:          "Azure OpenAI",
			Description:   "微软 Azure 云平台上的 OpenAI 服务，企业级安全和合规，支持 GPT-4 系列。",
			Protocol:      "azure",
			BaseURL:       "https://{resource}.openai.azure.com/openai/deployments/{deployment}",
			Website:       "https://azure.microsoft.com/products/ai-services/openai-service",
			SignupURL:     "https://azure.microsoft.com/free",
			DocsURL:       "https://learn.microsoft.com/azure/ai-services/openai",
			PricingURL:    "https://azure.microsoft.com/pricing/details/cognitive-services/openai-service",
			FreeTier:      "Azure 免费账户 $200 额度（30天）",
			Models:        []string{"gpt-4o", "gpt-4o-mini", "gpt-4", "gpt-35-turbo"},
			StreamSupport: true,
			Features:      []string{"企业级合规", "私有网络", "Azure AD 集成", "内容安全"},
		},
		{
			ID:            "gemini",
			Name:          "Google Gemini",
			Description:   "Google 自研 Gemini 系列模型，支持多模态，Gemini 1.5 Pro 支持 1M 上下文。",
			Protocol:      "gemini",
			BaseURL:       "https://generativelanguage.googleapis.com",
			Website:       "https://deepmind.google/technologies/gemini",
			SignupURL:     "https://aistudio.google.com/app/apikey",
			DocsURL:       "https://ai.google.dev/docs",
			PricingURL:    "https://ai.google.dev/pricing",
			FreeTier:      "Gemini 1.5 Flash 免费（限速），Pro 有免费额度",
			Models:        []string{"gemini-1.5-pro", "gemini-1.5-flash", "gemini-1.0-pro", "gemini-embedding"},
			StreamSupport: true,
			Features:      []string{"1M 上下文", "多模态", "Function Calling", "Embeddings"},
		},
		{
			ID:            "bedrock",
			Name:          "AWS Bedrock",
			Description:   "AWS 全托管模型服务，集成 Anthropic、Meta、Amazon 等多家模型，企业级安全。",
			Protocol:      "bedrock",
			BaseURL:       "https://bedrock-runtime.{region}.amazonaws.com",
			Website:       "https://aws.amazon.com/bedrock",
			SignupURL:     "https://aws.amazon.com/free",
			DocsURL:       "https://docs.aws.amazon.com/bedrock",
			PricingURL:    "https://aws.amazon.com/bedrock/pricing",
			FreeTier:      "AWS 免费套餐，部分模型有免费额度",
			Models:        []string{"anthropic.claude-3-sonnet", "meta.llama3-70b", "amazon.titan-text", "ai21.j2-ultra"},
			StreamSupport: true,
			Features:      []string{"多模型选择", "企业级安全", "私有部署", "Bedrock Agents"},
		},
		{
			ID:            "sagemaker",
			Name:          "AWS SageMaker",
			Description:   "AWS 模型部署平台，可自定义部署任意开源模型（vLLM、TGI 等），完全可控。",
			Protocol:      "sagemaker",
			BaseURL:       "https://runtime.sagemaker.{region}.amazonaws.com/endpoints/{endpoint}",
			Website:       "https://aws.amazon.com/sagemaker",
			SignupURL:     "https://aws.amazon.com/free",
			DocsURL:       "https://docs.aws.amazon.com/sagemaker",
			PricingURL:    "https://aws.amazon.com/sagemaker/pricing",
			FreeTier:      "AWS 免费套餐 2 个月（部分实例）",
			Models:        []string{"自定义部署任意开源模型", "Llama 3", "Mixtral", "Qwen"},
			StreamSupport: true,
			Features:      []string{"完全可控", "自定义模型", "自动扩缩容", "A/B 测试"},
		},
		{
			ID:            "cohere",
			Name:          "Cohere",
			Description:   "企业级 NLP 平台，Command 系列模型，擅长 RAG 和企业知识检索。",
			Protocol:      "cohere",
			BaseURL:       "https://api.cohere.ai",
			Website:       "https://cohere.com",
			SignupURL:     "https://dashboard.cohere.com/api-keys",
			DocsURL:       "https://docs.cohere.com",
			PricingURL:    "https://cohere.com/pricing",
			FreeTier:      "免费套餐（限速 10 次/分钟）",
			Models:        []string{"command-r-plus", "command-r", "command-light", "embed-english-v3"},
			StreamSupport: true,
			Features:      []string{"RAG 优化", "企业检索", "多语言", "Embeddings"},
		},
		{
			ID:            "mistral",
			Name:          "Mistral AI",
			Description:   "欧洲 AI 公司，Mistral/Mixtral 系列开源模型，性价比高，支持代码生成。",
			Protocol:      "mistral",
			BaseURL:       "https://api.mistral.ai/v1",
			Website:       "https://mistral.ai",
			SignupURL:     "https://console.mistral.ai/api-keys",
			DocsURL:       "https://docs.mistral.ai",
			PricingURL:    "https://mistral.ai/pricing",
			FreeTier:      "无免费额度，按量付费",
			Models:        []string{"mistral-large-latest", "mistral-medium-latest", "mistral-small-latest", "codestral-latest"},
			StreamSupport: true,
			Features:      []string{"开源模型", "代码生成", "Function Calling", "JSON Mode"},
		},
		{
			ID:            "huggingface",
			Name:          "Hugging Face",
			Description:   "全球最大的开源模型社区，Inference API 支持数万种开源模型，一键调用。",
			Protocol:      "huggingface",
			BaseURL:       "https://api-inference.huggingface.co",
			Website:       "https://huggingface.co",
			SignupURL:     "https://huggingface.co/settings/tokens",
			DocsURL:       "https://huggingface.co/docs/api-inference",
			PricingURL:    "https://huggingface.co/pricing",
			FreeTier:      "免费套餐（限速，模型需排队加载）",
			Models:        []string{"Llama 3", "Mixtral", "Qwen", "Phi-3", "数万种开源模型"},
			StreamSupport: false,
			Features:      []string{"开源模型", "社区驱动", "Datasets", "Spaces"},
		},
		{
			ID:            "replicate",
			Name:          "Replicate",
			Description:   "模型运行平台，支持数万种开源模型，包括图像生成、语音、视频等多模态模型。",
			Protocol:      "replicate",
			BaseURL:       "https://api.replicate.com",
			Website:       "https://replicate.com",
			SignupURL:     "https://replicate.com/account/api-tokens",
			DocsURL:       "https://replicate.com/docs",
			PricingURL:    "https://replicate.com/pricing",
			FreeTier:      "新用户赠送少量免费额度",
			Models:        []string{"LLaMA", "SDXL", "Whisper", "Suno", "数万种模型"},
			StreamSupport: false,
			Features:      []string{"多模态", "图像生成", "语音识别", "视频生成"},
		},
		{
			ID:            "together",
			Name:          "Together AI",
			Description:   "开源模型推理和微调平台，支持 Llama、Mixtral、Qwen 等，低延迟高吞吐。",
			Protocol:      "together",
			BaseURL:       "https://api.together.xyz/v1",
			Website:       "https://www.together.ai",
			SignupURL:     "https://api.together.xyz/settings/api-keys",
			DocsURL:       "https://docs.together.ai",
			PricingURL:    "https://www.together.ai/pricing",
			FreeTier:      "新用户赠送 $5 额度",
			Models:        []string{"Llama 3.1 405B", "Mixtral 8x22B", "Qwen 2.5", "DeepSeek V2"},
			StreamSupport: true,
			Features:      []string{"开源模型", "模型微调", "低延迟", "高吞吐"},
		},
		{
			ID:            "fireworks",
			Name:          "Fireworks AI",
			Description:   "前 Meta AI 团队创立的开源模型推理平台，主打低延迟和高吞吐，性价比高。",
			Protocol:      "fireworks",
			BaseURL:       "https://api.fireworks.ai/inference/v1",
			Website:       "https://fireworks.ai",
			SignupURL:     "https://fireworks.ai/settings/api-keys",
			DocsURL:       "https://docs.fireworks.ai",
			PricingURL:    "https://fireworks.ai/pricing",
			FreeTier:      "新用户赠送 $1 额度",
			Models:        []string{"Llama 3.1 405B", "Mixtral 8x7B", "Qwen 2.5", "DeepSeek V2"},
			StreamSupport: true,
			Features:      []string{"开源模型", "低延迟", "高吞吐", "Function Calling"},
		},
		{
			ID:            "groq",
			Name:          "Groq",
			Description:   "LPU 推理引擎，主打超快推理速度，延迟极低，适合实时对话场景。",
			Protocol:      "groq",
			BaseURL:       "https://api.groq.com/openai/v1",
			Website:       "https://groq.com",
			SignupURL:     "https://console.groq.com/keys",
			DocsURL:       "https://console.groq.com/docs",
			PricingURL:    "https://groq.com/pricing",
			FreeTier:      "免费套餐（限速 14400 请求/天，30 请求/分钟）",
			Models:        []string{"llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768", "gemma2-9b-it"},
			StreamSupport: true,
			Features:      []string{"超快速度", "低延迟", "免费套餐", "开源模型"},
		},
		// === 国内平台 ===
		{
			ID:            "zhipu",
			Name:          "智谱 AI (GLM)",
			Description:   "清华系创业公司，GLM 系列模型，中文能力强，GLM-4-Flash 永久免费。",
			Protocol:      "openai",
			BaseURL:       "https://open.bigmodel.cn/api/paas/v4",
			Website:       "https://www.zhipuai.cn",
			SignupURL:     "https://open.bigmodel.cn/usercenter/apikeys",
			DocsURL:       "https://open.bigmodel.cn/dev/api",
			PricingURL:    "https://open.bigmodel.cn/pricing",
			FreeTier:      "GLM-4-Flash 永久免费 + 新用户送 2000 万 Token",
			Models:        []string{"glm-4-plus", "glm-4.7-flash", "glm-4-flash", "glm-4v-plus"},
			StreamSupport: true,
			Features:      []string{"中文能力强", "永久免费模型", "Function Calling", "多模态"},
		},
		{
			ID:            "qwen",
			Name:          "阿里通义千问 (百炼)",
			Description:   "阿里巴巴达摩院出品，Qwen 系列模型，支持长文本和代码，新用户送代金券。",
			Protocol:      "openai",
			BaseURL:       "https://dashscope.aliyuncs.com/compatible-mode/v1",
			Website:       "https://tongyi.aliyun.com",
			SignupURL:     "https://dashscope.console.aliyun.com/apiKey",
			DocsURL:       "https://help.aliyun.com/zh/dashscope",
			PricingURL:    "https://www.aliyun.com/price/product#/dashscope/detail",
			FreeTier:      "新用户实名认证送代金券，部分模型有免费额度",
			Models:        []string{"qwen-max", "qwen-plus", "qwen-turbo", "qwen3-coder-plus"},
			StreamSupport: true,
			Features:      []string{"长文本", "代码能力", "多模态", "阿里云生态"},
		},
		{
			ID:            "ernie",
			Name:          "百度文心一言 (千帆)",
			Description:   "百度出品，ERNIE 系列模型，中文理解和知识问答强，ERNIE-Speed 永久免费。",
			Protocol:      "openai",
			BaseURL:       "https://qianfan.baidubce.com/v2",
			Website:       "https://yiyan.baidu.com",
			SignupURL:     "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
			DocsURL:       "https://cloud.baidu.com/doc/WENXINWORKSHOP/index.html",
			PricingURL:    "https://cloud.baidu.com/doc/WENXINWORKSHOP/s/hlrk4akp7",
			FreeTier:      "ERNIE-Speed 永久免费 + 各模型送 100 万 Token",
			Models:        []string{"ernie-4.5", "ernie-4.0", "ernie-3.5", "ernie-speed-128k"},
			StreamSupport: true,
			Features:      []string{"中文理解强", "知识问答", "永久免费模型", "百度生态"},
		},
		{
			ID:            "hunyuan",
			Name:          "腾讯混元",
			Description:   "腾讯出品，混元系列模型，混元 Lite 免费，新用户送 100 万 Token。",
			Protocol:      "openai",
			BaseURL:       "https://api.hunyuan.cloud.tencent.com/v1",
			Website:       "https://hunyuan.tencent.com",
			SignupURL:     "https://console.cloud.tencent.com/hunyuan/key",
			DocsURL:       "https://cloud.tencent.com/document/product/1729",
			PricingURL:    "https://cloud.tencent.com/document/product/1729/97731",
			FreeTier:      "混元 Lite 免费 + 新用户送 100 万 Token",
			Models:        []string{"hunyuan-t1", "hunyuan-turbos", "hunyuan-standard", "hunyuan-lite"},
			StreamSupport: true,
			Features:      []string{"免费模型", "腾讯生态", "Function Calling", "多模态"},
		},
		{
			ID:            "doubao",
			Name:          "字节跳动豆包 (火山方舟)",
			Description:   "字节跳动出品，豆包系列模型，火山引擎方舟平台，支持 DeepSeek 等第三方模型。",
			Protocol:      "openai",
			BaseURL:       "https://ark.cn-beijing.volces.com/api/v3",
			Website:       "https://www.doubao.com",
			SignupURL:     "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
			DocsURL:       "https://www.volcengine.com/docs/82379",
			PricingURL:    "https://www.volcengine.com/docs/82379/1099320",
			FreeTier:      "新用户送免费额度，部分模型有免费试用",
			Models:        []string{"doubao-pro-4k", "doubao-lite-4k", "deepseek-v3", "doubao-vision"},
			StreamSupport: true,
			Features:      []string{"字节生态", "多模型聚合", "Function Calling", "多模态"},
		},
		{
			ID:            "kimi",
			Name:          "月之暗面 (Kimi)",
			Description:   "月之暗面出品，Kimi 系列模型，超长上下文（200万 Token），适合长文档处理。",
			Protocol:      "openai",
			BaseURL:       "https://api.moonshot.cn/v1",
			Website:       "https://kimi.moonshot.cn",
			SignupURL:     "https://platform.moonshot.cn/console/api-keys",
			DocsURL:       "https://platform.moonshot.cn/docs",
			PricingURL:    "https://platform.moonshot.cn/docs/pricing/chat",
			FreeTier:      "新用户送免费额度（约 15 元）",
			Models:        []string{"kimi-k2.7", "kimi-k2.6", "kimi-k2", "moonshot-v1-128k"},
			StreamSupport: true,
			Features:      []string{"超长上下文", "长文档处理", "文件解析", "Function Calling"},
		},
		{
			ID:            "yi",
			Name:          "零一万物 (Yi)",
			Description:   "李开复创业公司，Yi 系列模型，开源和闭源都有，中文能力不错。",
			Protocol:      "openai",
			BaseURL:       "https://api.lingyiwanwu.com/v1",
			Website:       "https://www.lingyiwanwu.com",
			SignupURL:     "https://platform.lingyiwanwu.com/apikeys",
			DocsURL:       "https://platform.lingyiwanwu.com/docs",
			PricingURL:    "https://platform.lingyiwanwu.com/docs#%E4%BB%B7%E6%A0%BC",
			FreeTier:      "新用户送免费额度",
			Models:        []string{"yi-large", "yi-medium", "yi-spark", "yi-vision"},
			StreamSupport: true,
			Features:      []string{"开源模型", "中文能力", "Function Calling", "多模态"},
		},
		{
			ID:            "deepseek",
			Name:          "深度求索 (DeepSeek)",
			Description:   "深度求索出品，DeepSeek 系列模型，代码能力强，性价比极高，V3 模型性能接近 GPT-4。",
			Protocol:      "openai",
			BaseURL:       "https://api.deepseek.com/v1",
			Website:       "https://www.deepseek.com",
			SignupURL:     "https://platform.deepseek.com/api_keys",
			DocsURL:       "https://api-docs.deepseek.com",
			PricingURL:    "https://api-docs.deepseek.com/quick_start/pricing",
			FreeTier:      "新用户送 500 万 Token（约 5 元）",
			Models:        []string{"deepseek-chat", "deepseek-reasoner", "deepseek-coder", "deepseek-v3"},
			StreamSupport: true,
			Features:      []string{"代码能力强", "性价比高", "推理模型", "Function Calling"},
		},
		{
			ID:            "sensenova",
			Name:          "商汤日日新 (SenseNova)",
			Description:   "商汤科技出品，日日新系列模型，多模态能力强，支持图像生成和视频生成。",
			Protocol:      "openai",
			BaseURL:       "https://api.sensenova.cn/v1",
			Website:       "https://www.sensetime.com/cn",
			SignupURL:     "https://platform.sensenova.cn/center/apiKey",
			DocsURL:       "https://platform.sensenova.cn/doc",
			PricingURL:    "https://platform.sensenova.cn/price",
			FreeTier:      "新用户送免费额度",
			Models:        []string{"sensenova-6.8", "sensenova-5.0", "sensenova-4.0", "sensenova-vision"},
			StreamSupport: true,
			Features:      []string{"多模态", "图像生成", "视频生成", "Function Calling"},
		},
		{
			ID:            "siliconflow",
			Name:          "硅基流动 (SiliconFlow)",
			Description:   "国内开源模型聚合平台，一个 Key 调用 DeepSeek、Qwen、GLM、Llama 等几十个开源模型，小模型永久免费。",
			Protocol:      "openai",
			BaseURL:       "https://api.siliconflow.cn/v1",
			Website:       "https://siliconflow.cn",
			SignupURL:     "https://cloud.siliconflow.cn/account/ak",
			DocsURL:       "https://docs.siliconflow.cn",
			PricingURL:    "https://siliconflow.cn/pricing",
			FreeTier:      "注册送 ¥14，Qwen2.5-7B 等小模型永久免费",
			Models:        []string{"deepseek-ai/DeepSeek-V3", "Qwen/Qwen2.5-72B", "THUDM/glm-4-9b", "meta-llama/Meta-Llama-3.1-8B"},
			StreamSupport: true,
			Features:      []string{"多模型聚合", "永久免费模型", "国内直连", "高性价比"},
		},
		{
			ID:            "minimax",
			Name:          "MiniMax",
			Description:   "MiniMax 出品，ABAB 系列模型，语音和多模态能力强，支持语音合成和语音识别。",
			Protocol:      "openai",
			BaseURL:       "https://api.minimax.chat/v1",
			Website:       "https://www.minimaxi.com",
			SignupURL:     "https://platform.minimaxi.com/user-center/basic-information/interface-key",
			DocsURL:       "https://platform.minimaxi.com/document",
			PricingURL:    "https://platform.minimaxi.com/document/Price",
			FreeTier:      "新用户送免费额度",
			Models:        []string{"abab6.5s-chat", "abab6.5-chat", "abab5.5-chat", "speech-01"},
			StreamSupport: true,
			Features:      []string{"语音合成", "语音识别", "多模态", "Function Calling"},
		},
		{
			ID:            "spark",
			Name:          "讯飞星火",
			Description:   "科大讯飞出品，星火系列模型，语音和教育领域强，开放 Qwen 模型免费调用。",
			Protocol:      "openai",
			BaseURL:       "https://spark-api-open.xf-yun.com/v1",
			Website:       "https://xinghuo.xfyun.cn",
			SignupURL:     "https://console.xfyun.cn/services/bm35",
			DocsURL:       "https://www.xfyun.cn/doc/spark/Web.html",
			PricingURL:    "https://xinghuo.xfyun.cn/sparkapi",
			FreeTier:      "新用户送 Token，Qwen3.6-35B 等模型免费调用",
			Models:        []string{"spark4.0", "spark3.5", "spark3.1", "qwen3.6-35b"},
			StreamSupport: true,
			Features:      []string{"语音能力", "教育领域", "免费模型", "多模态"},
		},
	}
}
